import type { Author, Book, SiteContent } from "./types";

export const authorsSeed: Author[] = [
  { id: "a1", name: "İbn Ataullah el-İskenderî", photo: "https://www.ravzakitap.com/gelin-taci-566688-2009558-56-B.jpg", short_bio: "Şâzeliyye tarikatının üçüncü büyük mürşidi, Hikem-i Atâiyye müellifi (ö. 1309).", full_bio: "Tâceddîn Ebu'l-Fadl Ahmed b. Muhammed İbn Atâullah el-İskenderî (ö. 709/1309), İskenderiye'de doğmuş olup Şâzeliyye tarikatının üçüncü büyük mürşididir. Gençliğinde tasavvufa mesafeli durmuş, ancak Ebü'l-Abbas el-Mürsî ile tanışmasının ardından ona intisap ederek hayatını tasavvufa adamıştır.\n\nMaliki fıkhı ve Arapça konusunda derin bir ilme sahip olan İbn Atâullah, Ezher Camii'nde ders vermiş ve dönemin önde gelen alimlerinden biri olmuştur. İbn Teymiyye ile girdiği tartışmalar, tasavvuf-şeriat ilişkisi konusunda önemli tartışmalara zemin hazırlamıştır.\n\nEn meşhur eseri \"el-Hikem\" (Hikmetli Sözler), kısa ama derin anlamlı aforizmalardan oluşur ve yüzyıllardır İslam dünyasında en çok okunan tasavvufi eserlerden biri olmaya devam etmektedir." },
  { id: "a2", name: "İzz b. Abdüsselam", photo: "https://www.ravzakitap.com/ibadetlerin-hikmetleri-makasidul-ibadat-2023999-56-B.png", short_bio: "Sultânü'l-Ulemâ lakabıyla anılan, cesur duruşuyla efsaneleşen büyük Şâfiî fakihi (1181-1262).", full_bio: "İzzeddin Abdülaziz b. Abdüsselâm es-Sülemî (577-660/1181-1262), İslam tarihinin en cesur ve etkili alimlerinden biridir. Şam'da doğmuş, dönemin en prestijli ilim merkezlerinde eğitim almıştır. İlmi derinliği sayesinde \"Sultânü'l-Ulemâ\" (Alimlerin Sultanı) unvanını kazanmıştır.\n\nŞam ve Kahire'de müderrislik ve kadılık yapan İbn Abdüsselâm, zalim yöneticilere karşı cesur tutumu ile tanınmıştır. İslam hukukunda \"maslahat\" (kamu yararı) ilkesini sistemleştiren en önemli isimlerden biridir." },
  { id: "a3", name: "Nizamül Mülk", photo: "https://www.ravzakitap.com/siyasetnme-601046-2046677-60-B.jpg", short_bio: "Büyük Selçuklu Devleti'nin efsanevi veziri, Siyasetname müellifi (1018-1092).", full_bio: "Büyük Selçuklu Devleti'nin en parlak dönemlerine damgasını vuran Nizamülmülk, sadece bir vezir değil, aynı zamanda İslam siyaset düşüncesinin ve devlet yönetiminin temel taşlarını döşeyen bir dehadır. Sultan Alparslan ve Sultan Melikşah dönemlerinde yaklaşık otuz yıl boyunca vezirlik makamında bulunmuştur.\n\nSiyasetname adlı eseri, bugün bile devlet yönetimi üzerine yazılmış en önemli başvuru kaynaklarından biridir. 1092 yılında Haşhaşiler tarafından düzenlenen bir suikast sonucu şehit edilmiştir." },
  { id: "a4", name: "İmam Gazâlî", photo: "https://cdn.ravzakitap.com/nasihatul-muluk-612598-2058857-61-O.jpg", short_bio: "Hüccetü'l-İslâm, İslam düşüncesinin en etkili simalarından (1058-1111).", full_bio: "Ebû Hâmid Muhammed b. Muhammed el-Gazâlî (450-505/1058-1111), Horasan'ın Tûs şehrinde doğmuştur. Nizâmiye Medresesi'nde eğitim almış ve genç yaşta Bağdat Nizâmiye Medresesi'nin başmüderrisliğine getirilmiştir.\n\nBaşyapıtı \"İhyâu Ulûmi'd-Dîn\", İslam'ın ibadet, ahlak ve tasavvuf boyutlarını sistematik olarak ele alan ansiklopedik bir eserdir. \"Tehâfütü'l-Felâsife\" ile felsefeyi eleştirmiş, \"el-Munkız mine'd-Dalâl\" ile kendi manevi yolculuğunu anlatmıştır." },
  { id: "a5", name: "Ebü'l-Hasan en-Nûrî", photo: "https://www.ravzakitap.com/selamet-gemisi-muinus-sailin-min-fadli-rabbil-alemin-2018788-57-B.jpg", short_bio: "Bağdat tasavvuf mektebinin önde gelen simalarından, \"kalplerin sultanı\" (ö. 907).", full_bio: "Ebü'l-Hasan Ahmed b. Muhammed en-Nûrî el-Bağdâdî (ö. 295/907), Bağdat tasavvuf geleneğinin en önemli temsilcilerinden biridir. Cüneyd-i Bağdâdî'nin yakın dostu ve çağdaşı olan Nûrî, \"kalplerin sultanı\" olarak anılmıştır.\n\nTasavvufta \"îsâr\" (başkalarını kendine tercih etme) kavramının en güzel örneklerinden birini sergilemiştir." },
  { id: "a6", name: "İmam Nevevî", photo: "https://cdn.ravzakitap.com/hakikat-bahcesi-bustanul-arifin-2024166-58-O.jpg", short_bio: "Hadis ve fıkıh ilminin büyük otoritesi, Riyazüs-Salihin müellifi (1233-1277).", full_bio: "Muhyiddîn Ebû Zekeriyyâ Yahyâ b. Şeref en-Nevevî (631-676/1233-1277), Suriye'nin Neva kasabasında doğmuş, Şam'da yetişmiştir. Şâfiî mezhebinin en büyük otoritelerinden biri olarak kabul edilir.\n\nRiyazüs-Salihin, Kırk Hadis, el-Ezkâr ve Müslim Şerhi gibi eserleri İslam dünyasında en çok okunan ve referans alınan kaynaklardandır." },
  { id: "a7", name: "Mehmed Said Efendi", photo: "https://www.ravzakitap.com/ey-kizim-vezaiful-inas-2054798-60-B.jpg", short_bio: "Osmanlı dönemi müellifi, aile ve ahlak konularında eser veren alim.", full_bio: "Mehmed Said Efendi, Osmanlı döneminin önemli müelliflerinden biridir. Özellikle aile hayatı, kadın eğitimi ve ahlak konularında kaleme aldığı eserleriyle tanınmıştır.\n\n\"Vezâif-i İnâs\" (Ey Kızım) adlı eseri, genç kızlara ve hanımlara yönelik nasihatler içeren, döneminin en popüler eserlerinden biri olmuştur." },
  { id: "a8", name: "İbn Hacer El Heytemi", photo: "https://www.ravzakitap.com/salat-ve-selamin-dindeki-yeri-eddurrul-mendud-2043258-59-B.jpg", short_bio: "Şâfiî mezhebinin büyük alimlerinden, çok sayıda eserin müellifi (1504-1567).", full_bio: "Şihâbüddîn Ahmed b. Muhammed İbn Hacer el-Heytemî (909-974/1504-1567), Mısır'da doğmuş ve dönemin en önemli Şâfiî alimlerinden biri olmuştur. Fıkıh, hadis ve tasavvuf alanlarında sayısız eser kaleme almıştır." },
  { id: "a9", name: "Mehmed Faik Bey", photo: "https://www.ravzakitap.com/mutlu-aile-saadet-i-aile-2046678-60-B.jpg", short_bio: "Osmanlı dönemi müellifi, aile hayatı konusunda eser veren yazar.", full_bio: "Mehmed Faik Bey, Osmanlı döneminin son dönemlerinde yaşamış, aile hayatı ve toplumsal konularda eserler kaleme almış bir müelliftir." },
  { id: "a10", name: "Celalüddin es-Suyûtî", photo: "https://www.ravzakitap.com/dosta-hicret-2012027-56-B.jpg", short_bio: "İslam dünyasının en üretken alimlerinden, 500'den fazla eserin müellifi (1445-1505).", full_bio: "Celâlüddîn Abdurrahmân b. Ebî Bekr es-Süyûtî (849-911/1445-1505), Mısır'da doğmuş ve İslam tarihinin en üretken alimlerinden biri olmuştur. Tefsir, hadis, fıkıh, tarih ve dil alanlarında 500'den fazla eser kaleme almıştır." }
];

export const booksSeed: Book[] = [
  { id: "gelin-taci", title: "Gelin Tacı - Tâcü'l-Arûs", author_id: "a1", cover: "https://www.ravzakitap.com/gelin-taci-566688-2009558-56-B.jpg", summary: "İbn Ataullah el-İskenderî hazretlerinin kaleme aldığı bu eser, tasavvuf yolunun inceliklerini ve nefis terbiyesinin sırlarını ele alan nadide bir klasiktir.", isbn: "9786258431643", published_date: "2023", genre: "Tasavvuf", sales_links: [{ name: "Ravza Kitap", url: "https://www.ravzakitap.com/gelin-taci-566688", price: 60 }, { name: "Kitapyurdu", url: "https://www.kitapyurdu.com/kitap/gelin-taci-tacul-arus/690475.html", price: 130 }, { name: "Trendyol", url: "https://www.trendyol.com/sr?q=gelin+taci+dibace", price: 65 }, { name: "Hepsiburada", url: "https://www.hepsiburada.com/ara?q=gelin+taci+dibace", price: 68 }, { name: "Amazon", url: "https://www.amazon.com.tr/s?k=gelin+taci+dibace", price: 70 }] },
  { id: "ibadetlerin-hikmetleri", title: "İbadetlerin Hikmetleri - Makâsıdü'l-İbâdât", author_id: "a2", cover: "https://www.ravzakitap.com/ibadetlerin-hikmetleri-makasidul-ibadat-2023999-56-B.png", summary: "Sultânü'l-Ulemâ İzz b. Abdüsselam'ın, İslam ibadetlerinin hikmetlerini ve amaçlarını ele aldığı bu eseri, ibadeti bilinçle yerine getirmenin önemini vurgular.", isbn: "9786258431612", published_date: "2023", genre: "İslam / Hikmet", sales_links: [{ name: "Ravza Kitap", url: "https://www.ravzakitap.com/ibadetlerin-hikmetleri-makasidul-ibadat", price: 56 }, { name: "Kitapyurdu", url: "https://www.kitapyurdu.com/kitap/ibadetlerin-hikmetleri-makasidul-ibadat-namaz-oruc-hac/682181.html", price: 100 }, { name: "Trendyol", url: "https://www.trendyol.com/sr?q=ibadetlerin+hikmetleri+dibace", price: 60 }, { name: "Hepsiburada", url: "https://www.hepsiburada.com/ara?q=ibadetlerin+hikmetleri+dibace", price: 62 }, { name: "Amazon", url: "https://www.amazon.com.tr/s?k=ibadetlerin+hikmetleri+dibace", price: 65 }] },
  { id: "siyasetname", title: "Siyasetnâme", author_id: "a3", cover: "https://www.ravzakitap.com/siyasetnme-601046-2046677-60-B.jpg", summary: "Büyük Selçuklu veziri Nizamülmülk'ün devlet yönetimi, adalet ve ahlak üzerine kaleme aldığı bu şaheser, siyaset düşüncesinin temel taşlarından biridir.", isbn: "9786258431766", published_date: "2024", genre: "Siyaset / Tarih", sales_links: [{ name: "Ravza Kitap", url: "https://www.ravzakitap.com/siyasetn%C3%A2me-601046", price: 100 }, { name: "Kitapyurdu", url: "https://www.kitapyurdu.com/kitap/siyasetname/729388.html", price: 185 }, { name: "Trendyol", url: "https://www.trendyol.com/sr?q=siyasetname+dibace", price: 110 }, { name: "Hepsiburada", url: "https://www.hepsiburada.com/ara?q=siyasetname+dibace", price: 115 }, { name: "Amazon", url: "https://www.amazon.com.tr/s?k=siyasetname+dibace", price: 120 }] },
  { id: "ahiret-azigi", title: "Ahiret Azığı - Zâd-ı Âhiret", author_id: "a4", cover: "https://www.ravzakitap.com/ahiret-azigi-2031427-58-B.jpg", summary: "Hüccetü'l-İslâm İmam Gazâlî'nin ahiret hayatına hazırlık, ölüm ve sonrasına dair kaleme aldığı bu eser, müminler için bir zâd-ı âhiret rehberidir.", isbn: "9786258431711", published_date: "2024", genre: "Tasavvuf / Ahlak", sales_links: [{ name: "Ravza Kitap", url: "https://www.ravzakitap.com/ahiret-azigi", price: 60 }, { name: "Kitapyurdu", url: "https://www.kitapyurdu.com/kitap/ahiret-azigi-zadi-ahiret/716735.html", price: 145 }, { name: "Trendyol", url: "https://www.trendyol.com/sr?q=ahiret+azigi+dibace", price: 65 }, { name: "Hepsiburada", url: "https://www.hepsiburada.com/ara?q=ahiret+azigi+dibace", price: 68 }, { name: "Amazon", url: "https://www.amazon.com.tr/s?k=ahiret+azigi+dibace", price: 70 }] },
  { id: "nasihatul-muluk", title: "Nasîhatü'l-Mülûk", author_id: "a4", cover: "https://www.ravzakitap.com/nasihatul-muluk-612598-2058857-61-B.jpg", summary: "İmam Gazâlî'nin hükümdarlara ve yöneticilere hitaben kaleme aldığı bu nasihatname, adil yönetimin ilkelerini ve devlet adamlığının erdemlerini anlatır.", isbn: "9786258431780", published_date: "2024", genre: "Siyaset / Ahlak", sales_links: [{ name: "Ravza Kitap", url: "https://www.ravzakitap.com/nasihatul-muluk-612598", price: 72 }, { name: "Kitapyurdu", url: "https://www.kitapyurdu.com/kitap/nasihatulmuluk/742323.html", price: 165 }, { name: "Trendyol", url: "https://www.trendyol.com/sr?q=nasihatul+muluk+dibace", price: 78 }, { name: "Hepsiburada", url: "https://www.hepsiburada.com/ara?q=nasihatul+muluk+dibace", price: 80 }, { name: "Amazon", url: "https://www.amazon.com.tr/s?k=nasihatul+muluk+dibace", price: 85 }] },
  { id: "selamet-gemisi", title: "Selamet Gemisi - Muînü's-Sâilîn", author_id: "a5", cover: "https://www.ravzakitap.com/selamet-gemisi-muinus-sailin-min-fadli-rabbil-alemin-2018788-57-B.jpg", summary: "Ebü'l-Hasan en-Nûrî'nin tasavvuf yolcularına rehberlik eden bu eseri, manevi kurtuluşun yollarını ve sâliklerin dikkat etmesi gereken hususları anlatır.", isbn: "9786258431698", published_date: "2024", genre: "Tasavvuf", sales_links: [{ name: "Ravza Kitap", url: "https://www.ravzakitap.com/selamet-gemisi-muinus-sailin-min-fadli-rabbil-alemin", price: 54 }, { name: "Kitapyurdu", url: "https://www.kitapyurdu.com/kitap/selamet-gemisi-muinussailin-min-fadli-rabbilalemin/700763.html", price: 140 }, { name: "Trendyol", url: "https://www.trendyol.com/sr?q=selamet+gemisi+dibace", price: 58 }, { name: "Hepsiburada", url: "https://www.hepsiburada.com/ara?q=selamet+gemisi+dibace", price: 60 }, { name: "Amazon", url: "https://www.amazon.com.tr/s?k=selamet+gemisi+dibace", price: 62 }] },
  { id: "hakikat-bahcesi", title: "Hakikat Bahçesi - Bustânü'l-Ârifîn", author_id: "a6", cover: "https://www.ravzakitap.com/hakikat-bahcesi-bustanul-arifin-2024166-58-B.jpg", summary: "İmam Nevevî'nin âriflerin makamlarını ve tasavvufî hakikatleri ele aldığı bu eser, ilim ve irfanın birleştiği nadide bir klasiktir.", isbn: "9786258431704", published_date: "2024", genre: "Tasavvuf / Hikmet", sales_links: [{ name: "Ravza Kitap", url: "https://www.ravzakitap.com/hakikat-bahcesi-bustanul-arifin", price: 60 }, { name: "Kitapyurdu", url: "https://www.kitapyurdu.com/kitap/hakikat-bahcesi-bustanularifin/711216.html", price: 150 }, { name: "Trendyol", url: "https://www.trendyol.com/sr?q=hakikat+bahcesi+dibace", price: 65 }, { name: "Hepsiburada", url: "https://www.hepsiburada.com/ara?q=hakikat+bahcesi+dibace", price: 68 }, { name: "Amazon", url: "https://www.amazon.com.tr/s?k=hakikat+bahcesi+dibace", price: 70 }] },
  { id: "ey-kizim", title: "Ey Kızım - Vezâifü'l-İnâs", author_id: "a7", cover: "https://www.ravzakitap.com/ey-kizim-vezaiful-inas-2054798-60-B.jpg", summary: "Osmanlı döneminden günümüze ulaşan bu nadide eser, genç kızlara ve hanımlara yönelik ahlaki ve manevi nasihatler içermektedir.", isbn: "9786258431773", published_date: "2024", genre: "Ahlak / Aile", sales_links: [{ name: "Ravza Kitap", url: "https://www.ravzakitap.com/ey-kizim-vezaiful-inas", price: 48 }, { name: "Kitapyurdu", url: "https://www.kitapyurdu.com/kitap/ey-kizim-vezaifulinas/737297.html", price: 125 }, { name: "Trendyol", url: "https://www.trendyol.com/sr?q=ey+kizim+dibace", price: 52 }, { name: "Hepsiburada", url: "https://www.hepsiburada.com/ara?q=ey+kizim+dibace", price: 55 }, { name: "Amazon", url: "https://www.amazon.com.tr/s?k=ey+kizim+dibace", price: 58 }] },
  { id: "dosta-hicret", title: "Dosta Hicret - Büşra'l-Keîb Bi-Likâi'l-Habîb", author_id: "a10", cover: "https://www.ravzakitap.com/dosta-hicret-2012027-56-B.jpg", summary: "Manevi yolculuğun inceliklerini ve hakikate ulaşma sürecini ele alan, tasavvuf edebiyatının seçkin eserlerinden biridir.", isbn: "9786258431650", published_date: "2024", genre: "Tasavvuf", sales_links: [{ name: "Ravza Kitap", url: "https://www.ravzakitap.com/dosta-hicret", price: 45.5 }, { name: "Kitapyurdu", url: "https://www.kitapyurdu.com/kitap/dosta-hicret-busralkeib-bilikailhabib/692767.html", price: 135 }, { name: "Trendyol", url: "https://www.trendyol.com/sr?q=dosta+hicret+dibace", price: 50 }, { name: "Hepsiburada", url: "https://www.hepsiburada.com/ara?q=dosta+hicret+dibace", price: 52 }, { name: "Amazon", url: "https://www.amazon.com.tr/s?k=dosta+hicret+dibace", price: 55 }] },
  { id: "mutlu-aile", title: "Mutlu Aile - Saadet-i Aile", author_id: "a9", cover: "https://www.ravzakitap.com/mutlu-aile-saadet-i-aile-2046678-60-B.jpg", summary: "İslami perspektiften mutlu ve huzurlu bir aile hayatının temellerini anlatan, evlilik ve aile ilişkileri üzerine rehber bir eserdir.", isbn: "9786258431759", published_date: "2024", genre: "Aile / Ahlak", sales_links: [{ name: "Ravza Kitap", url: "https://www.ravzakitap.com/mutlu-aile-saadet-i-aile", price: 48 }, { name: "Kitapyurdu", url: "https://www.kitapyurdu.com/kitap/mutlu-aile-saadeti-aile/729389.html", price: 130 }, { name: "Trendyol", url: "https://www.trendyol.com/sr?q=mutlu+aile+dibace", price: 52 }, { name: "Hepsiburada", url: "https://www.hepsiburada.com/ara?q=mutlu+aile+dibace", price: 55 }, { name: "Amazon", url: "https://www.amazon.com.tr/s?k=mutlu+aile+dibace", price: 58 }] },
  { id: "salat-selam", title: "Salat ve Selamın Dindeki Yeri - ed-Dürrü'l-Mendûd", author_id: "a8", cover: "https://www.ravzakitap.com/salat-ve-selamin-dindeki-yeri-eddurrul-mendud-2043258-59-B.jpg", summary: "Hz. Peygamber'e salât ü selâm getirmenin fazileti, adabı ve hikmetlerini ele alan kapsamlı bir eserdir.", isbn: "9786258431742", published_date: "2024", genre: "Hadis / Siyer", sales_links: [{ name: "Ravza Kitap", url: "https://www.ravzakitap.com/salat-ve-selamin-dindeki-yeri-eddurrul-mendud", price: 130 }, { name: "Kitapyurdu", url: "https://www.kitapyurdu.com/kitap/salat-ve-selamin-dindeki-yeri-eddurrulmendud/726331.html", price: 145 }, { name: "Trendyol", url: "https://www.trendyol.com/sr?q=salat+selam+dibace", price: 140 }, { name: "Hepsiburada", url: "https://www.hepsiburada.com/ara?q=salat+selam+dibace", price: 145 }, { name: "Amazon", url: "https://www.amazon.com.tr/s?k=salat+selam+dibace", price: 150 }] }
];

export const contentsSeed: SiteContent[] = [
  { key: "SITE_TITLE", value: "Dibace Yayınları", description: "Web sitesinin ana başlığı" },
  { key: "HEADER_TAGLINE", value: "Edebiyatın Önsözü", description: "Logonun yanındaki slogan" },
  { key: "ABOUT_US_TITLE", value: "Hakkımızda", description: "Hakkımızda sayfası başlığı" },
  { key: "ABOUT_US_CONTENT", value: "Dibace Yayınları, edebiyatın derinliklerine yolculuk eden bir yayın evidir.", description: "Hakkımızda sayfası içeriği" },
  { key: "FOOTER_ADDRESS", value: "Dervişali Mahallesi. Draman Caddesi. 3/A Fatih / İstanbul", description: "Alt kısımdaki adres bilgisi" },
  { key: "CONTACT_PHONE", value: "+90 212 000 00 00", description: "İletişim sayfasındaki telefon" },
  { key: "CONTACT_EMAIL", value: "info@dibace.com", description: "İletişim sayfasındaki e-posta" },
  { key: "HOME_BRAND_LABEL", value: "DİBACE YAYINLARI", description: "Hero slider üstündeki marka etiketi" },
  { key: "HOME_HERO_1_TITLE", value: "Kelimelerin Kadim Yolculuğu", description: "Slider 1 başlık" },
  { key: "HOME_HERO_1_SUBTITLE", value: "Geçmişin mirası, geleceğin ışığıyla buluşuyor.", description: "Slider 1 alt başlık" },
  { key: "HOME_HERO_1_BUTTON", value: "HİKAYEMİZ", description: "Slider 1 buton" },
  { key: "HOME_HERO_2_TITLE", value: "Mürekkebin Asaleti", description: "Slider 2 başlık" },
  { key: "HOME_HERO_2_SUBTITLE", value: "Söz uçar, yazı kalır. Zamana direnen eserler.", description: "Slider 2 alt başlık" },
  { key: "HOME_HERO_2_BUTTON", value: "ESERLERİMİZ", description: "Slider 2 buton" },
  { key: "HOME_HERO_3_TITLE", value: "Hakikatin ve Hikmetin İzinde", description: "Slider 3 başlık" },
  { key: "HOME_HERO_3_SUBTITLE", value: "Her kitap, yeni bir dünyaya açılan kapıdır.", description: "Slider 3 alt başlık" },
  { key: "HOME_HERO_3_BUTTON", value: "YAZARLARIMIZ", description: "Slider 3 buton" },
  { key: "HOME_QUOTE_TEXT", value: "\"Zaman kılıç gibidir; <span class=\"accent-text\">biz zamana kalan sözü</span> yayımlarız.\"", description: "Hero altı özlü söz" },
  { key: "HOME_FEATURED_SUBTITLE", value: "Kataloğumuzdan", description: "Öne çıkanlar üst başlık" },
  { key: "HOME_FEATURED_TITLE", value: "Öne Çıkan Eserler", description: "Öne çıkanlar başlık" },
  { key: "HOME_FEATURED_VIEW_ALL", value: "Tümünü Gör", description: "Öne çıkanlar tümünü gör metni" },
  { key: "HOME_PHILOSOPHY_1_TITLE", value: "İlim", description: "Felsefe 1 başlık" },
  { key: "HOME_PHILOSOPHY_1_DESC", value: "Akademik titizlikle seçilmiş, kaynağı sahih klasik eserler.", description: "Felsefe 1 açıklama" },
  { key: "HOME_PHILOSOPHY_2_TITLE", value: "İrfan", description: "Felsefe 2 başlık" },
  { key: "HOME_PHILOSOPHY_2_DESC", value: "Satırların ötesine geçen, kalbe dokunan hikmet arayışı.", description: "Felsefe 2 açıklama" },
  { key: "HOME_PHILOSOPHY_3_TITLE", value: "Hikmet", description: "Felsefe 3 başlık" },
  { key: "HOME_PHILOSOPHY_3_DESC", value: "Varlığın gayesini ve eşyanın hakikatini kavrayan derin bakış.", description: "Felsefe 3 açıklama" }
];

export function contentMap(contents: SiteContent[]) {
  return Object.fromEntries(contents.map((item) => [item.key, item.value])) as Record<string, string>;
}
